DROP TABLE IF EXISTS DB_TEST;

CREATE TABLE DB_TEST (
  id UUID PRIMARY KEY,
  account VARCHAR(250) NOT NULL,
  destination VARCHAR(250) NOT NULL,
  startDate VARCHAR(250) NOT NULL,
  endDate VARCHAR(250) NOT NULL,
  status VARCHAR(250) NOT NULL,
  costPerMinute VARCHAR(10) NOT NULL
);